openapi: 3.0.0
info:
   title: H plus Sports API - Product Service
   version: 1.0.0
paths:
  /products/{productId}:
    get:
      parameters: 
        - in: path
          name: productId
          required: true
          schema:
            type: integer
            example: 12312
        - in: header
          name: customer-security-header
          required: false
          schema:
            type: integer
            example: 123-908-783
      responses:
        200:
          description: Specific product id
          content:
            application/json:
              schema:
                $ref:  '#/components/schemas/Product'
            application/xml:
              schema:
                $ref: '#/components/schemas/Product'
        500:
          $ref: '#/components/responses/500ApiError'
  /products:
    post:
      description: Add products to catelog
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        200:
          description: The product has been created 
        500:
          $ref: '#/components/responses/500ApiError'
    get:
      parameters: 
        - $ref: '#/components/parameters/pageNumber'
        - $ref: '#/components/parameters/pageSize'
        
      responses:
        200:
          description: This is a list of the products in the catelog
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    id:
                      type: integer
                      example: 400
                    name:
                      type: string
                      example: L emon water
                    desc: 
                      type: string
                      example : products which are available 
        500:
          $ref: '#/components/responses/500ApiError'
components:
  parameters:
    pageNumber:
      in: query 
      name: pageNumber
      description: page number
      required: false
      schema:
        type: integer
        example: 1
    pageSize:
      in: query
      name: pageSize
      description: page size
      required: false
      schema:
        type: integer
        example: 10
        maximum: 100
  schemas:
    Product:
      type: object
      required: 
       - name
       - id
      properties:
        id:
          type: integer
          example: 400
        name:
          type: string
          example: L emon water
        desc: 
          type: string
          example : products which are available
        imageTitle:
          type: string
          example: lemon
        imageUrl:
          type: string
          example: http://www.naturalhealth365.com/wp-content/uploads/2015/04/lemon-water.jpg
  responses:
    500ApiError:
      description: This is unexpected error
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: string
                example: 500
              message:
                type: string
                example: This is an error
                
          
                
  