/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.14).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.InlineResponse200;
import io.swagger.model.InlineResponse500;
import io.swagger.model.Product;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-11-24T16:39:28.790Z[GMT]")
@Api(value = "products", description = "the products API")
public interface ProductsApi {

    @ApiOperation(value = "", nickname = "productsGet", notes = "", response = InlineResponse200.class, responseContainer = "List", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "This is a list of the products in the catelog", response = InlineResponse200.class, responseContainer = "List"),
        @ApiResponse(code = 500, message = "This is unexpected error", response = InlineResponse500.class) })
    @RequestMapping(value = "/products",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<InlineResponse200>> productsGet(@ApiParam(value = "page number") @Valid @RequestParam(value = "pageNumber", required = false) Integer pageNumber, @Max(100) @ApiParam(value = "page size", allowableValues = "") @Valid @RequestParam(value = "pageSize", required = false) Integer pageSize);


    @ApiOperation(value = "", nickname = "productsPost", notes = "Add products to catelog", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "The product has been created"),
        @ApiResponse(code = 500, message = "This is unexpected error", response = InlineResponse500.class) })
    @RequestMapping(value = "/products",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> productsPost(@ApiParam(value = ""  )  @Valid @RequestBody Product body);


    @ApiOperation(value = "", nickname = "productsProductIdGet", notes = "", response = Product.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Specific product id", response = Product.class),
        @ApiResponse(code = 500, message = "This is unexpected error", response = InlineResponse500.class) })
    @RequestMapping(value = "/products/{productId}",
        produces = { "application/json", "application/xml" }, 
        method = RequestMethod.GET)
    ResponseEntity<Product> productsProductIdGet(@ApiParam(value = "",required=true) @PathVariable("productId") Integer productId,@ApiParam(value = "" ) @RequestHeader(value="customer-security-header", required=false) Integer customerSecurityHeader);

}
